Bump project-factory to ~> 11
terraform-google-modules/terraform-google-bootstrap pull request #134
Opened 2021-11-21 00:47 UTC by cagataygurturk

Fixes #129

2021-11-21 14:39 UTC, cagataygurturk commented
I am not sure why integration tests did not pass. Locally they did.

2021-11-22 17:04 UTC, morgante requested changes

2021-11-22 17:04 UTC, morgante commented on main.tf
> +  version                     = "~> 11"
We pin to a major version.

```suggestion
  version                     = "~> 11.2"
```

2021-11-22 17:04 UTC, morgante commented on modules/cloudbuild/main.tf
> +  version                     = "~> 11"
```suggestion
  version                     = "~> 11.2"
```

2021-11-22 17:33 UTC, morgante approved these changes

2021-11-22 18:01 UTC, bharathkkb approved these changes

2021-11-22 18:01 UTC, merged