DRAFT: add connection module
terraform-google-modules/terraform-google-bootstrap pull request #312
Opened 2024-08-16 11:28 UTC by caetano-colin

WIP

2024-08-16 13:43 UTC, caetano-colin commented
/gcbrun

2024-08-16 15:03 UTC, daniel-cit commented
/gcbrun

2024-08-16 18:59 UTC, daniel-cit commented
/gcbrun

2024-08-16 19:48 UTC, apeabody commented
/gcbrun

2024-08-17 00:11 UTC, daniel-cit commented
/gcbrun

2024-08-17 00:44 UTC, daniel-cit commented on examples/cloudbuild_repo_connection_github/variables.tf
> +  description = "The HTTPS clone URL of the test repository, ending with .git."
```suggestion
variable "repository_url" {
  description = "The HTTPS clone URL of the repository, ending with .git."
```

2024-08-17 00:44 UTC, daniel-cit commented on examples/cloudbuild_repo_connection_github/variables.tf
> +  description = "The name of the test repository."
```suggestion
variable "repository_name" {
  description = "The name of the repository."
```

2024-08-17 00:49 UTC, daniel-cit commented on modules/cloudbuild_repo_connection/variables.tf
> +variable "cloudbuild_repos" {
```suggestion
variable "cloud_build_repositories" {
```

2024-08-17 00:50 UTC, daniel-cit commented on modules/cloudbuild_repo_connection/variables.tf
> +  description = "Default resources location"
```suggestion
variable "region" {
  description = "Resources location"
```

2024-08-17 00:50 UTC, daniel-cit commented on modules/cloudbuild_repo_connection/variables.tf
> +    repo_url  = string,
```suggestion
    repository_name = string,
    repository_url  = string,
```

2024-08-17 02:46 UTC, daniel-cit commented on test/integration/cloudbuild_repo_connection_github/cloudbuild_repo_connection_github_test.go
> +		repository := gcloud.Run(t, fmt.Sprintf("builds repositories describe %s", repoName), gcloud.WithCommonArgs([]string{"--project", project_id, "--region", location, "--connection", connection_name,
using `gcloud.RunF` would make the code easier to read

2024-08-17 02:47 UTC, daniel-cit commented
/gcbrun

2024-08-18 20:25 UTC, daniel-cit commented
/gcbrun

2024-08-19 14:15 UTC, daniel-cit commented
/gcbrun

2024-08-19 14:40 UTC, daniel-cit commented on test/integration/cloudbuild_repo_connection_github/cloudbuild_repo_connection_github_test.go
> +		repository := gcloud.Runf(t, "builds repositories describe %s --project %s, --region %s --connection %s", repoName, project_id, location, connection_name)
```suggestion
		repository := gcloud.Runf(t, "builds repositories describe %s --project %s --region %s --connection %s", repoName, project_id, location, connection_name)
```

2024-08-19 14:40 UTC, daniel-cit commented on test/integration/cloudbuild_repo_connection_gitlab/cloudbuild_repo_connection_gitlab_test.go
> +		repository := gcloud.Runf(t, "builds repositories describe %s --project %s, --region %s --connection %s", repoName, project_id, location, connection_name)
```suggestion
		repository := gcloud.Runf(t, "builds repositories describe %s --project %s --region %s --connection %s", repoName, project_id, location, connection_name)
```

2024-08-19 16:05 UTC, daniel-cit commented
/gcbrun

2024-08-19 18:04 UTC, apeabody commented on modules/cloudbuild_repo_connection/versions.tf
> +      version = "0.12.0"
```suggestion
      version = ">= 0.12.0"
```

2024-08-19 18:04 UTC, apeabody commented on modules/cloudbuild_repo_connection/versions.tf
> +      version = "3.6.2"
```suggestion
      version = ">= 3.6.2"
```

2024-08-19 18:05 UTC, apeabody commented on modules/cloudbuild_repo_connection/versions.tf
> +  required_version = ">=0.15.0"
Needed for `optional()` in variables.tf

```suggestion
  required_version = ">=1.3"
```

2024-08-19 19:22 UTC, daniel-cit commented
/gcbrun

2024-08-19 20:18 UTC, daniel-cit commented
/gcbrun

2024-08-20 19:52 UTC, apeabody requested changes
Thanks @caetano-colin!  A few minor things I noted during the final review.

2024-08-20 19:52 UTC, apeabody commented on examples/cloudbuild_repo_connection_gitlab/main.tf
> +  source = "../../modules/cloudbuild_repo_connection"
For examples please use the registry and version (e.g. https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/examples/tf_cloudbuild_builder_simple/main.tf#L18), and the CI will automatically replace with this prior source line when running lint and tests.

2024-08-20 19:52 UTC, apeabody commented on test/integration/cloudbuild_repo_connection_gitlab/cloudbuild_repo_connection_gitlab_test.go
> +		assert.Equal(resourcesLocation, connectionLocation, "Connection location should be 'us-central'.")
`us-central1`? Perhaps better to use `resourcesLocation` in `fmt.Sprintf`.

```suggestion
		assert.Equal(resourcesLocation, connectionLocation, "Connection location should be 'us-central'.")
```

2024-08-20 19:52 UTC, apeabody commented on test/integration/cloudbuild_repo_connection_github/cloudbuild_repo_connection_github_test.go
> +		assert.Equal(resourcesLocation, connectionLocation, "Connection location should be 'us-central'.")
`us-central1`? Perhaps better to use `resourcesLocation` in `fmt.Sprintf`.

```suggestion
		assert.Equal(resourcesLocation, connectionLocation, "Connection location should be 'us-central`'.")
```

2024-08-21 11:10 UTC, caetano-colin commented
@apeabody thank you for the review! I implemented the requested changes. Regarding the module registry version I put:

```terraform
version = "~> 9.0"
```

I'm assuming that would be the module version, If that is not correct please let me know.

2024-08-21 16:25 UTC, apeabody commented
> @apeabody thank you for the review! I implemented the requested changes. Regarding the module registry version I put:
> 
> ```hcl
> version = "~> 9.0"
> ```
> 
> I'm assuming that would be the module version, If that is not correct please let me know.

Yeah, that should be fine for now.  Thanks!

2024-08-21 16:26 UTC, apeabody commented
/gcbrun

2024-08-21 18:37 UTC, apeabody commented
@caetano-colin - The last INT test didn't complete before timeout, might want to bump slightly: https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/build/int.cloudbuild.yaml#L15

2024-08-21 23:43 UTC, apeabody approved these changes

2024-08-21 23:43 UTC, apeabody commented
@gtsorbo do you want to review before merging?

2024-08-22 11:16 UTC, caetano-colin commented
> @caetano-colin - The last INT test didn't complete before timeout, might want to bump slightly: https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/build/int.cloudbuild.yaml#L15

Created a commit that increases the timeout in 10minutes

2024-08-22 15:09 UTC, daniel-cit commented
/gcbrun

2024-08-22 18:02 UTC, daniel-cit approved these changes
LGTM

2024-08-22 18:02 UTC, merged